version: '3.7'

services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: koa-api
    container_name: koa-api
    restart: always
    env_file: .env  
    environment: 
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_DBNAME=$MONGO_DBNAME
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports: 
      - '8000:5000'
    networks: 
      - app-network
    volumes: 
      - ${PWD}:/home/node/app
      - ${PWD}/node_modules:/home/node/app/node_modules
    links: 
      - mongo
      - redis
    depends_on: 
      - mongo
    command: npm run prod
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports: 
      - '27017:27017'
    networks: 
      - app-network
    volumes: 
      - ${PWD}/dbdata:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    env_file: .env
    environment: 
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports: 
      - '6379:6379'
    networks:
      - 'app-network'
    volumes: 
      - ${PWD}/redis-data:/var/lib/redis
    
networks: 
  app-network:
    driver: bridge

volumes: 
  dbdata:
  node_modules: 
  redis_data: